// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(WorksDbContext))]
    [Migration("20251126140832_FixGuidFK")]
    partial class FixGuidFK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Domain.Entities.Work", b =>
                {
                    b.Property<Guid>("WorkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnalysisCompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AnalysisRequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PlagiarismFlag")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReportId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmissionTime")
                        .HasColumnType("TEXT");

                    b.HasKey("WorkId");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("Status");

                    b.HasIndex("StudentId");

                    b.ToTable("Works");
                });
#pragma warning restore 612, 618
        }
    }
}
