// <auto-generated />
using System;
using Analysis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analysis.Infrastructure.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251126140722_ExtendModel")]
    partial class ExtendModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Domain.Entities.AnalysisRecord", b =>
                {
                    b.Property<Guid>("AnalysisRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignmentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WorkId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AnalysisRecordId");

                    b.HasIndex("AnalysisRecordId");

                    b.HasIndex("WorkId");

                    b.ToTable("Analysis");
                });

            modelBuilder.Entity("Domain.Entities.Report", b =>
                {
                    b.Property<Guid>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AnalysisRecordId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FileId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPlagiarism")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SimilarityPercentage")
                        .HasColumnType("REAL");

                    b.HasKey("ReportId");

                    b.HasIndex("AnalysisRecordId");

                    b.HasIndex("ReportId");

                    b.ToTable("Report");
                });
#pragma warning restore 612, 618
        }
    }
}
