// <auto-generated />
using System;
using Analysis.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Analysis.Infrastructure.Migrations
{
    [DbContext(typeof(AnalysisDbContext))]
    [Migration("20251126132250_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("Domain.Entities.WorkAnalysis", b =>
                {
                    b.Property<Guid>("AnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PlagiarismFlag")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReportFileId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("AnalysisId");

                    b.HasIndex("AnalysisId");

                    b.HasIndex("WorkId");

                    b.ToTable("Analysis");
                });
#pragma warning restore 612, 618
        }
    }
}
